port: 8080

replication:
  connections:
    - type: postgresql
      uri: !env PS_SOURCE_URI
      sslmode: disable

storage:
  type: postgresql
  uri: !env PS_STORAGE_URI
  sslmode: disable

client_auth:
  jwks:
    keys:
      - kty: oct
        kid: petnote-local-hs256
        alg: HS256
        k: !env PS_JWT_SECRET_BASE64URL
  audience:
    - powersync

sync_config:
  path: /config/sync-config.yaml
